server:
  port: 9527

spring:
  application:
    name: cloud-gateway #微服务的名字注册进入consul或nacos服务列表
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    #配置网关
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service           #动态提供路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-06-30T10:52:01.007349800+08:00[Asia/Shanghai]   #在xxx时间之后才可访问
#            - Before=2024-06-30T10:55:55.007349800+08:00[Asia/Shanghai]  #在xxx时间之前才可访问
#            - Between=2024-06-30T10:58:01.007349800+08:00[Asia/Shanghai],2024-06-30T10:58:30.007349800+08:00[Asia/Shanghai]  #在xxx时间到xxx时间之间才可访问
#            - Cookie=username,jks  #携带cookie 且key=username,value=jks
#            - Header=X-Request-Id,\d+ #请求头要由X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.jksIsBest.com #Host Route Predicate 接收一组参数，一组匹配的域名列表，这个模板是一个 ant 分隔的模板，用.号作为分隔符。它通过参数中的主机地址作为匹配规则。
#            - Query=username,\d+  #要有参数名username并且值还要是整数才能路由
#            - RemoteAddr=192.168.200.1/24  # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
#            - Method=post #配置某个请求地址，只能用Get/Post方法访问，方法限制
            - My=gold
#            - name: My
#              args:
#                userType: gold

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
  #        uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/** # 断言，路径相匹配的进行路由 默认路径
#            - Path=/gateway/filter/** #路径拆分
#            - Path=/alinaBecker/Robin/{segment}
          filters:
            - My=atguigu
#            - RedirectTo=302,https://www.yycdh91.com/
#            - SetPath=/pay/gateway/{segment}
#            - PrefixPath=/pay  #为路径添加前缀
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1 #请求头kv，若参数多个就写多行
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
#            - RemoveRequestHeader=sec-fetch-site  #删除请求头中的sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,ABCD-UPDATEbcda #更改请求头中的sec-fetch-mode
#            - AddRequestParameter=customerId,114504 # 新增请求参数Parameter：k ，v
#            - RemoveRequestParameter=customerName  # 删除请求参数customerName，就算携带了customerName，也为null
#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除


